import torch

class MatrixConfig:
    """
    Configuration for Indefinite Hermitian Matrix Generation.
    """
    def __init__(
        self, 
        n_ant=64,   # b: Matrix size (b x b)
        rank=1,     # a: Rank of the underlying matrix
        device=None
    ):
        self.n_ant = n_ant
        self.rank = rank
        self.device = device or ("cuda" if torch.cuda.is_available() else "cpu")


class HollowIndefiniteMatrixGenerator:
    """
    Generates a b x b Hermitian matrix based on a rank-a construction
    where eigenvalues can be positive or negative (Indefinite),
    and sets the diagonal terms to 0.
    """
    def __init__(self, config: MatrixConfig):
        self.config = config
        self.b = config.n_ant
        self.a = config.rank
        self.device = config.device

        # Pre-compute the mask to zero out the diagonal
        # Shape: (1, b, b) for efficient broadcasting
        self.mask = (1 - torch.eye(self.b, device=self.device)).unsqueeze(0)

    def __call__(self, batch_size=1):
        """
        Generates the matrix S.
        
        Math: S = (L @ D @ L^H) * mask
        Where D is a diagonal matrix with mixed signs.

        Returns:
            torch.Tensor: Shape (batch_size, b, b), complex64/128
        """
        # 1. Generate random complex basis vectors L of shape (Batch, b, a)
        real_L = torch.randn(batch_size, self.b, self.a, device=self.device)
        imag_L = torch.randn(batch_size, self.b, self.a, device=self.device)
        L = torch.complex(real_L, imag_L)

        # 2. Generate random REAL eigenvalues D with mixed signs
        # Shape: (Batch, a). We use randn to ensure mix of pos/neg values.
        D = torch.randn(batch_size, self.a, device=self.device)

        # 3. Construct S_full = L @ diag(D) @ L^H
        # Optimization: Scale L by D before multiplication to avoid creating diag matrix
        # L_scaled shape: (Batch, b, a)
        L_scaled = L * D.unsqueeze(1) 
        
        # S_full shape: (Batch, b, b)
        S_full = torch.matmul(L_scaled, L.transpose(-2, -1).conj())
        # 4. Apply Zero Diagonal constraint
        S = S_full * self.mask

        return S

class ThetaToDiagonalMatrix:
    """
    Converts a tensor of 2*b interleaved real/imaginary numbers into 
    a b x b complex diagonal matrix.
    """
    def __init__(self, config: MatrixConfig):
        self.device = config.device
        self.n_ant = config.n_ant

    def __call__(self, theta: torch.Tensor):
        # Move to device if one was specified during init
        if self.device is not None:
            theta = theta.to(self.device)

        # 1. Identify dimensions
        batch_size, two_b_1 = theta.shape
        b_1 = two_b_1 // 2
        if b_1 != int(self.n_ant - 1):
            raise ValueError(
                f"Input vector size mismatch: expected {int(self.n_ant - 1)} "
                f"antenna pairs (2*(n_ant-1)/2), got {b_1}."
            )
        # 2. Reshape into (Batch, b-1, 2) to separate Real and Imaginary parts

        theta_view = theta.view(batch_size, b_1, 2)
        
        # 3. Construct the complex vector for the "rest" of the antennas
        # Shape: (Batch, b-1)
        rest_complex = torch.complex(theta_view[..., 0], theta_view[..., 1])
        
        # 4. Create the fixed first term (1 + 0j)
        # Shape: (Batch, 1)
        first_complex = torch.ones((batch_size, 1), device=theta.device, dtype=rest_complex.dtype)
        
        # 5. Concatenate: [1, g2, g3, ... gb]
        # Shape: (Batch, b)
        full_complex_vector = torch.cat([first_complex, rest_complex], dim=1)
        
        # 6. Embed into a diagonal matrix
        # Shape: (Batch, b, b)
        diagonal_matrix = torch.diag_embed(full_complex_vector)
        
        return diagonal_matrix

class GtoV:
    """V Matrix created based on gains parameter theta."""
    def __init__(self, config):
        # Assuming S is generated by the Generator Class we made earlier
        # You might want to pass the actual S matrix here or generated it
        self.device = config.device

    def __call__(self, G, S):
        S = S.to(dtype=G.dtype, device=G.device)
        V = G @ S @ G.transpose(-2, -1).conj()
        return V

class VtoRow:
    def __init__(self, config):
        # Assuming S is generated by the Generator Class we made earlier
        # You might want to pass the actual S matrix here or generated it
        self.device = config.device

    def __call__(self, V):
        row = V[:,0]
        return row