# -----------------------------------------------------------------------------
# WandB logging configuration
# -----------------------------------------------------------------------------
logging:
  project: falcon_gaincal                   # WandB project name
  group: experiment_000                     # Logical group or experiment name
  dir: ${hydra:run.dir}                     # Log directory (Hydra's resolved run path)
# Addcpupertask on terminal command
# -----------------------------------------------------------------------------
# Directory configuration
# -----------------------------------------------------------------------------
paths:
  import: "./src"                       # Local folder(s) with user-defined code (e.g. model.py)
  buffer: ${hydra:run.dir}/sim_dir      # Directory where Falcon stores simulated training data
  graph: ${hydra:run.dir}/graph_dir     # Directory for serialized graph and trained networks

# -----------------------------------------------------------------------------
# Training buffer parameters
# -----------------------------------------------------------------------------
buffer:
  min_training_samples: 2048            # Minimum samples before training starts
  max_training_samples: 2048            # Maximum number of samples retained in buffer
  validation_window_size: 256           # Size of validation split (for early stopping)
  resample_batch_size: 0                # Number of new samples drawn per resampling step
  keep_resampling: true                 # Continue resampling after reaching max samples
  resample_interval: 10                 # Resample every N training epochs

# -----------------------------------------------------------------------------
# Graph definition using declarative YAML
# -----------------------------------------------------------------------------
graph:
  z:
    # evidence: [obsx]
    parents: []
    simulator: 
      _target_: falcon.contrib.HypercubeMappingPrior
      priors:
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
      - [uniform, -0.0001, 0.0001]
    # estimator:
    #   _target_: falcon.contrib.SNPE_A
    #   embedding:
    #     _target_: model.E
    #     _input_: [obsx]
    #   net_type: zuko_gf                   # zuko_gf, nice, sospf, maf, gf
    #   # theta_norm = true
    #   # norm_momentum: 0.003
    #   # log_ratio_threshold: -20          # Stability cutoff for log ratios
    #   # discard_samples: true
    #   gamma: 0.5
    #   num_epochs: 50
    #   batch_size: 128
    #   lr: 0.01
    #   early_stop_patience: 32
    #   lr_decay_factor: 0.1
    #   scheduler_patience: 16
    #   # use_log_update: true
    #   # adaptive_momentum: false
    #   # sample_reference_posterior: false
    #   # use_best_models_during_inference: true
    #   # reset_network_after_pause: false
    # ray:
    #   num_gpus: 1.0

  pw:
    evidence: [obsx]
    parents: []
    simulator: 
      _target_: falcon.contrib.HypercubeMappingPrior
      priors: 
      - ['uniform', -4, -2]
      - ['uniform', -3, -2]
    estimator:
      _target_: falcon.contrib.SNPE_A
      embedding:
        _target_: model.E
        _input_: [obsx]
      net_type: maf                   # zuko_gf, nice, sospf, maf, gf
      # theta_norm = true
      # norm_momentum: 0.003
      # log_ratio_threshold: -20          # Stability cutoff for log ratios
      # discard_samples: true
      gamma: 0.5
      num_epochs: 5
      batch_size: 128
      lr: 0.01
      early_stop_patience: 32
      lr_decay_factor: 0.1
      scheduler_patience: 16
      # use_log_update: true
      # adaptive_momentum: false
      # sample_reference_posterior: false
      # use_best_models_during_inference: true
      # reset_network_after_pause: false
    ray:
      num_gpus: 1.0

  gains:
    parents: [z]
    simulator: 
      _target_: model.creategainfromtheta

  stacked_uv:
    parents: [gains]
    simulator: 
      _target_: model.createuvmapfromgain

  noisestacked_uv:
    parents: [gains]
    simulator:
      _target_: model.createnoiseuvmapfromgain

  df:
    parents: [pw]
    simulator:
      _target_: model.createdffrompw

  bt:
    parents: [df]
    simulator:
      _target_: model.createbtfromdf

  image:
    parents: [bt]
    simulator:
      _target_: model.createimagefrombtandgauss
  
  uvimage:
    parents: [image]
    simulator:
      _target_: model.createuvimagefromimage

  noiseimage:
    parents: [uvimage]
    simulator:
      _target_: model.Noise

  tracked_uv:
    parents: [uvimage, stacked_uv]
    simulator:
      _target_: model.createsvfromuvimageandtracks

  normed_tracked_uv:
    parents: [tracked_uv]
    simulator:
      _target_: model.createnvfromsv

  noisetracked_uv:
    parents: [noiseimage, noisestacked_uv]
    simulator:
      _target_: model.createsvfromnoiseandtracks

  noisenormed_tracked_uv:
    parents: [noisetracked_uv]
    simulator:
      _target_: model.createnoisenvfromsv
  
  x:
    parents: [normed_tracked_uv, noisenormed_tracked_uv]
    simulator:
      _target_: model.createxfromnvandnoisenv

  obsx:
    parents: [x]
    simulator:
      _target_: model.createobsxfromx
    observed: "data/normed_tracked_uvobs.npy"

# -----------------------------------------------------------------------------
# Sampling configuration (posterior draws after training)
# -----------------------------------------------------------------------------
sample:
  prior:
    n: 250
    path: samples_prior.joblib
  proposal:
    n: 250
    path: samples_proposal.joblib
  posterior:
    n: 500                                 # Number of posterior samples to draw
    path: samples_posteriorxyz.joblib      # Output path for saved samples (under hydra.run.dir)